config/routes.rb
Rails.application.routes.draw do
  root to: "main_page#index"

  post "/authenticate-user", to: "main_page#authenticate_user", as: :authenticate_user

  get "/home", to: "users#home", as:"users_home"
  get "/new_user", to: "users#new", as: "new_user"
  post "/new_user", to: "users#create", as: "create_user"
  get "/profile/:user_profile_id", to: "users#profile", as: "profile_user"
  get "/artist/:artist_id", to: "artists#show", as: "artist"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_attached_file :avatar, styles: {medium: "300x300", small: "40x40"}, default_url: "banda_foto.png"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_and_belongs_to_many :members, class_name: "User"
  has_many :posts

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, class_name: "User"

end

app/models/post.rb
class  Post < ActiveRecord::Base
  

  belongs_to :artist
end

app/models/user.rb
class User < ActiveRecord::Base
  has_attached_file :avatar, styles: {medium: "300x300", small: "40x40"}, default_url: "perfil.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  has_many :friendships 
  has_many :friends, through: :friendships
  has_and_belongs_to_many :artists
  
  def authenticate_password?(password)
    self.password == password
  end

  def be_friend_of(friend)
    Friendship.create(user: self, friend: friend)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def check_user
    unless session[:user].present?
      redirect_to root_path
    end
    @user = User.find session[:user]
    @friends = @user.friends
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  layout 'users'

  before_filter :check_user
  def new
  end

  def show
    @artist = Artist.find(params[:artist_id])
  end
end

app/controllers/main_page_controller.rb
class MainPageController < ApplicationController
 layout "main_page"
  def index
  end
  def authenticate_user
    if params[:username].present? && params[:password].present?
      unless @user = User.where(username: params[:username]).first
        
      end
       if @user.authenticate_password?(params[:password])
         session[:user] = @user.id
         redirect_to users_home_path
       end

    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 layout "users"

 before_filter :check_user, except: [:new, :create]
 before_filter :set_attributes, except: [:new, :create]
  def home
    @posts = @user.artists.map(&:posts).flatten.compact.sort{|a,b| b.created_at <=> a.created_at }
  end

  def new
    @user = User.new
    render :new, layout: false
  end

  def create
    user_params = params.require(:user).permit(:name, :username, :password, :email, :birthdate, :avatar)
    User.create(user_params)
    redirect_to :root
  end
  def profile
    @user_profiled = User.find(params[:user_profile_id])
    @artists_followed = @user_profiled.artists
  end

  private
  def set_attributes
    @friends = @user.friends
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/show.html.erb
<%= content_for :head do %>
  <style>
  .artist-image{
    float: left;  
    width: 150px;
    margin-bottom: 20px;
  }
  .artist-name{
    color: #FFFFFF;
    display: inline;
    float: left;
    margin-top: 50px;
    margin-left: 100px;
    font-size: 300%;
  }
  .artist-head-container{
    margin-bottom: 20px;
  }
  .artist-songs{
    padding-top: 10px;
    clear: both;
    background: #171717;
    height: 500px;
  }
  .container-title{
    color: #FFFFFF;
    margin-left: 20px;
  }
  </style>
<% end %>

<div class="profile-container">
  <div class="artist-head-container">
    <%= image_tag @artist.avatar.url(:medium), alt: @artist.name, class: "artist-image"%>
    <h1 class="artist-name"><%= @artist.name%></h1>
  </div>

  <div class="artist-songs">
    <h2 class="container-title">Musicas:</h2>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunderWeb</title>
    <%= csrf_meta_tags %>
    <%= yield :stylesheets %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :javascript%>
  </body>
</html>

app/views/layouts/main_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunderWeb</title>
    <%= csrf_meta_tags %>
    <%= yield :stylesheets %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= yield :javascript%>
  </body>
</html>

app/views/layouts/users.html.erb
<DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title> Munder - musica underground para todos os gostos </title>
  <%= stylesheet_link_tag "users"%>
  <%= yield :head %>
  </head>
  <body>
    <div class="topo">
      <%= link_to(image_tag("munder_logo-pqn.png", alt: "Munder"), users_home_path)%>
      <ul>
        <li><a href="<%= users_home_path%>">Home</a></li>
        <li><a href="<%= profile_user_path(user_profile_id: @user.id)%>">Perfil</a><%= image_tag @user.avatar.url(:small)%></li>
        </ul>
      <div class="busca">
        <form action="#" method="get">
          <input type="search" name="busca" placeholder="Buscar">
          <input type="submit"/>
        </form>
      </div>

          <br/>
        </div>
        <div class="menu">
          <ul>
            <li><a href="Munder_Home.html">Shows</a></li>
            <li><a href="Munder_Home.html">Bandas</a></li>
            <li><a href="Munder_Home.html">Ranking</a></li>
            <li><a href="Munder_Home.html">Playlists</a></li>
          </ul>
        </div>
        <div class="tudo"> 
          <div class="musicas">
            <div class="menu-musica">
              <h2><b>Suas Músicas</b></h2>
              <ul>
                <li><a href="#"><%= image_tag "playlist.png", alt: "playlist"%> Playlists</a></li>
                <li><a href="#"><%= image_tag "musica.png", alt: "Músicas"%>Músicas</a></li>
                <li><a href="#"><%= image_tag "albuns.png", alt: "Álbuns"%>Álbuns</a></li>
                <li><a href="#"><%= image_tag "artista.png", alt: "Artistas"%>Artistas</a></li>
              </ul>
            </div>
            <div class="recentes">
              <h2><b>Recém tocadas</b></h2>
              <div class="musica-tocada">
                <%= image_tag "cd.jpg", alt: "capa do cd"%>
                <a href="#">The number of the beast</a><br/>
                <a href="#">Iron Maiden</a><br/>
                <a href="#">The number of the beast</a>
              </div>
            </div>
          </div>
          <%= render partial: "shared/friends_side_menu.html.erb"%>
          <div class="center-box">
            <%= yield %>
          </div>
        </div>
            
      </body>
          <div class="footer">
            <h5>Munder ©</h5>
          </div>
            </html>

app/views/main_page/index.html.erb
<%= content_for :stylesheets do %>
  <%= stylesheet_link_tag "home_page"%>
  <style>
    .munder-image{
      width: 300px;
      float: left;
    }
  </style>
<% end %>  
<div class='center-box'>
  <div class='logo'>
    <%= image_tag "munder-500.png", alt: "Munder", class: "munder-image"%>
  </div>
  <div class="login-container">
    <div class='login-form'>
      <%= form_tag authenticate_user_path, method: :post do %>
        <%= text_field_tag :username, nil, placeholder: "Username"%>
        <%= password_field_tag :password, nil, placeholder: "Password" %>
        <div>
          <%= submit_tag "Log in", class: "submit" %>
          <%= link_to "cadastre-se", new_user_path %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_friends_side_menu.html.erb
<div class="amigos">
  <h2><b>Amigos</b></h2>
  <% @friends.each do |friend| %> 
    <div class="amigo-perfil">
      <%= image_tag friend.avatar.url(:small), alt: "amigo"%>
      <a href="#"><%= link_to friend.name, profile_user_path(user_profile_id: friend.id) %></a><br/>
      <div class="nome-musica">
        <a href="#"><%= image_tag "musica-pqn.png", alt: "música"%> The number of the beast</a>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_posts.html.erb
<% content_for :head do%>
  <style>
    .artist-post-image{
      width: 50px;

    }
  </style>
<% end  %>

<% @posts.each do |post| %>
  <div class="post">
  <%= image_tag post.artist.avatar.url(:small), class: "artist-post-image"%>
  <div class="nome-horario"><a href="<%= artist_path(artist_id: post.artist.id)%>"><%= post.artist.name.capitalize%></a><br/>
    <h5><%= post.created_at.strftime("%d/%m/%y %H:%M")%></h5><br/>
  </div>
  <p><%= post.content.html_safe%></p>
  <div class="comentario"><a href="#">Comentários</a><br/></div>
</div>
<% end %>

app/views/users/home.html.erb
<%=  render 'shared/posts' %>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title> Cadastre-se | Munder </title>
<%= stylesheet_link_tag "subscription"%>
</head>
<body>
<div class="topo-menu">
  <a href="index.html">home</a>
  <a href="munder_home.html">demo</a>
</div>
<div class="header">
  <%= image_tag "header-cadastro.png", alt: "Munder"%>
</div>
<div class="formulario">
  <h1><b>Cadastro</b></h1>
  <%= form_for @user, url: create_user_path, html: { multipart: true } do |form| %>
    <label>nome:</label><%= form.text_field :name%>
    <label>username:</label>  <%= form.text_field :username%>
    <label>senha:</label> <%= form.password_field :password%>
    <label>email:</label><%= form.text_field :email%>
    <label>data de nascimento:</label><%= form.date_field :birthdate%>
    <label>Foto:</label><%= form.file_field :avatar %>
    <%= form.submit "confirmar"%>
  <% end %>
</div>

<div class="footer">
  <h5>Munder ©</h5>
</div>

</body>
</html>

app/views/users/profile.html.erb
<% content_for :head do%>
  <style>
  h1,h2,h3{
    color: #FFFFFF;
  }
.profile_container{
  
}
.profile_picture{
  width: 150px;
  height: 150px;
  border-radius: 50%;
  float: left;
  margin-bottom: 30px;
}
.user-name{
  color: #FFFFFF;
  display: inline;
  float: left;
  margin-top: 50px;
  margin-left: 100px;
  font-size: 300%;
}
.followed-bands-container{
  padding: 20px;
  height: 150px;
  background: #171717;
  clear: both;
  margin-top: 30px;
}
.artist-box-container{
  float: left;
  margin-right: 21px;
  text-align: center;
}
span{
  color: #FFFFFF;
}
.artist-image{
  margin-top: 22px;
  width: 100px;
}
</style>

<% end %>

<div class="profile-container">
  <div class="profile-header">
    <%= image_tag @user_profiled.avatar.url(:medium), alt: "Profile_picture", class: "profile_picture"%>
    <h1 class="user-name"><%= @user_profiled.name %></h1>
  </div>
  <div class="followed-bands-container">
    <h2>Bandas curtidas:</h2>
    <% @artists_followed.last(5).each do |artist|%>
      <div class="artist-box-container">
        <a href="<%= artist_path(artist_id: artist.id)%>">
        <%= image_tag artist.avatar.url(:medium), alt: artist.name, class: "artist-image"%><br/>
        <span><%= artist.name.capitalize%></span>
        </a>
      </div>
    <% end %>
  </div>
  <div class="followed-bands-container">
    <h2>Amigos:</h2>
    <% @user_profiled.friends.last(5).each do |artist|%>
      <div class="friends-box-container">
        <%= image_tag artist.avatar.url(:medium), alt: artist.name, class: "artist-image"%><br/>
        <span><%= artist.name.capitalize%></span>
      </div>
    <% end %>
  </div>
</div>